### PR TITLE
feature/graphql-interface

### PR DESCRIPTION
**Pull request by KalleChen**
Fixes # (issue)

## Why do we need this PR?
- Add codegen to generate graqhql interface

## How did you address the issue?
- Add codegen dependencies

<br />  

> ## PR readiness check list
> - [ ] Did it pass the lint check?
> - [ ] Did you test this PR?  
> - [ ] Did you explain the changes clearly?
> - [ ] Did you reference the correct issues?

### CODE REVIEW

**Review by ruofanwei — APPROVED** [review]

**Comment by apo1798** [comment]
@KalleChen 想請教一下我這邊好像跑不了，不知道是不是 docker 裡面連結到外網的問題  

```bash
frontend-1  | [SUCCESS] Generate outputs
frontend-1  | [FAILED] 
frontend-1  | [FAILED]         Failed to load schema from http://localhost:8000/graphql/:
frontend-1  | [FAILED] 
frontend-1  | [FAILED]         connect ECONNREFUSED 127.0.0.1:8000
frontend-1  | [FAILED]         Error: connect ECONNREFUSED 127.0.0.1:8000
frontend-1  | [FAILED]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
frontend-1  | [FAILED] 
frontend-1  | [FAILED]         GraphQL Code Generator supports:
frontend-1  | [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
frontend-1  | [FAILED]           - Introspection JSON File
frontend-1  | [FAILED]           - URL of GraphQL endpoint
frontend-1  | [FAILED]           - Multiple files with type definitions (glob expression)
frontend-1  | [FAILED]           - String in config file
frontend-1  | [FAILED] 
frontend-1  | [FAILED]         Try to use one of above options and run codegen again.
frontend-1  | [FAILED] 
frontend-1  | [FAILED]       
frontend-1  | Running lifecycle hook "afterStart" scripts...
frontend-1  | [CLI] Loading Schemas
frontend-1  | error Command failed with exit code 1.
frontend-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by KalleChen** [comment]
@apo1798 嗯我有發現，我這幾天找時間看一下問題，thanks～

**Comment by KalleChen** [comment]
@apo1798 上面的問題解決了，有空再幫我試試看～

**Review by apo1798 — APPROVED** [review]
感謝 Kalle 哩

**Pull request merged**
